import React from "react";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";

import styles from "@/styles/Home.module.css";

import { KanbanType } from "@/types";
import { KanbanList } from "@/components";
import { useAppDispatch } from "@/hooks";
import { setKanban } from "@/store";
import { setKanbanList } from "@/store";
import { KanbanApi } from "@/api";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: { data: KanbanType[] }) {
  const dispatch = useAppDispatch();

  React.useEffect(() => {
    dispatch(setKanban(null));
    dispatch(setKanbanList(data));
  }, []);

  return (
    <>
      <Head>
        <title>Канбаны</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <KanbanList kanbans={data} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const data = await KanbanApi.getKanbanList();

  return {
    props: {
      data,
    },
  };
};
